In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/kaggle/input/video-game-sales/vgsales.csv', index_col = ['Rank'])
data

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Rank,,,,,,,,,,
1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [3]:
data['Dataset_Type'] = 'Sports'

In [4]:
data.columns

Index(['Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales', 'Dataset_Type'],
      dtype='object')

In [5]:
data.dtypes

Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
Dataset_Type     object
dtype: object

In [6]:
data

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Dataset_Type
Rank,,,,,,,,,,,
1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,Sports
2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,Sports
3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,Sports
4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,Sports
5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,Sports
...,...,...,...,...,...,...,...,...,...,...,...
16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,Sports
16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,Sports
16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,Sports
16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,Sports
16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,Sports

In [7]:
data['Year'] = 2022

In [8]:
data

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Dataset_Type
Rank,,,,,,,,,,,
1,Wii Sports,Wii,2022,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,Sports
2,Super Mario Bros.,NES,2022,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,Sports
3,Mario Kart Wii,Wii,2022,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,Sports
4,Wii Sports Resort,Wii,2022,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,Sports
5,Pokemon Red/Pokemon Blue,GB,2022,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,Sports
...,...,...,...,...,...,...,...,...,...,...,...
16596,Woody Woodpecker in Crazy Castle 5,GBA,2022,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,Sports
16597,Men in Black II: Alien Escape,GC,2022,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,Sports
16598,SCORE International Baja 1000: The Official Game,PS2,2022,Racing,Activision,0.00,0.00,0.00,0.00,0.01,Sports
16599,Know How 2,DS,2022,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,Sports
16600,Spirits & Spells,GBA,2022,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,Sports

In [9]:
d = {
    'A': 3,
    'B': 4
}
d

{'A': 3, 'B': 4}

In [10]:
d['A']

3

In [11]:
d['C'] = 5

In [12]:
d

{'A': 3, 'B': 4, 'C': 5}

In [13]:
data.head()

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Dataset_Type
Rank,,,,,,,,,,,
1,Wii Sports,Wii,2022,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,Sports
2,Super Mario Bros.,NES,2022,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,Sports
3,Mario Kart Wii,Wii,2022,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,Sports
4,Wii Sports Resort,Wii,2022,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,Sports
5,Pokemon Red/Pokemon Blue,GB,2022,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,Sports

In [14]:
data.insert(4, 'Library', 'Pandas',allow_duplicates = True)

In [15]:
data

,Name,Platform,Year,Genre,Library,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Dataset_Type
Rank,,,,,,,,,,,,
1,Wii Sports,Wii,2022,Sports,Pandas,Nintendo,41.49,29.02,3.77,8.46,82.74,Sports
2,Super Mario Bros.,NES,2022,Platform,Pandas,Nintendo,29.08,3.58,6.81,0.77,40.24,Sports
3,Mario Kart Wii,Wii,2022,Racing,Pandas,Nintendo,15.85,12.88,3.79,3.31,35.82,Sports
4,Wii Sports Resort,Wii,2022,Sports,Pandas,Nintendo,15.75,11.01,3.28,2.96,33.00,Sports
5,Pokemon Red/Pokemon Blue,GB,2022,Role-Playing,Pandas,Nintendo,11.27,8.89,10.22,1.00,31.37,Sports
...,...,...,...,...,...,...,...,...,...,...,...,...
16596,Woody Woodpecker in Crazy Castle 5,GBA,2022,Platform,Pandas,Kemco,0.01,0.00,0.00,0.00,0.01,Sports
16597,Men in Black II: Alien Escape,GC,2022,Shooter,Pandas,Infogrames,0.01,0.00,0.00,0.00,0.01,Sports
16598,SCORE International Baja 1000: The Official Game,PS2,2022,Racing,Pandas,Activision,0.00,0.00,0.00,0.00,0.01,Sports
16599,Know How 2,DS,2022,Puzzle,Pandas,7G//AMES,0.00,0.01,0.00,0.00,0.01,Sports
16600,Spirits & Spells,GBA,2022,Platform,Pandas,Wanadoo,0.01,0.00,0.00,0.00,0.01,Sports