In [1]:
import pandas as pd

In [2]:
#Creating data from read cv method
df = pd.read_csv('/kaggle/input/video-game-sales/vgsales.csv')
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [3]:
s1 = pd.read_csv("/kaggle/input/video-game-sales/vgsales.csv", usecols = ['Name', 'Platform'])
s1

                                                   Name Platform
0                                            Wii Sports      Wii
1                                     Super Mario Bros.      NES
2                                        Mario Kart Wii      Wii
3                                     Wii Sports Resort      Wii
4                              Pokemon Red/Pokemon Blue       GB
...                                                 ...      ...
16593                Woody Woodpecker in Crazy Castle 5      GBA
16594                     Men in Black II: Alien Escape       GC
16595  SCORE International Baja 1000: The Official Game      PS2
16596                                        Know How 2       DS
16597                                  Spirits & Spells      GBA

[16598 rows x 2 columns]

In [4]:
s2 = pd.read_csv("/kaggle/input/video-game-sales/vgsales.csv", usecols = ['Name'])
s2

                                                   Name
0                                            Wii Sports
1                                     Super Mario Bros.
2                                        Mario Kart Wii
3                                     Wii Sports Resort
4                              Pokemon Red/Pokemon Blue
...                                                 ...
16593                Woody Woodpecker in Crazy Castle 5
16594                     Men in Black II: Alien Escape
16595  SCORE International Baja 1000: The Official Game
16596                                        Know How 2
16597                                  Spirits & Spells

[16598 rows x 1 columns]